4GeeksAcademy/Grupo5_EthosVolunteeringPlatform

src/front/js/component/impactCounter.js, src/front/js/component/navbar.js
- src/front/js/component/navbar.js: delete dropdown.
- src/front/js/component/impactCounter.js: Delete import.
=> Delete dropdown from navbar

src/front/js/component/contactForm.js, src/front/js/pages/Contacto.js, src/front/styles/home.css
src/front/js/component/contactForm.js: Create the component contactForm with its infomation require.
src/front/js/pages/Contacto.js: Add component contactForm at the page Contact.
src/front/styles/home.css: create to classes for contactForm. 
1- A wrapper form for all the content.
2- A class to change the color-text of select.
=> Add contact page.

src/front/js/component/contactForm.js, src/front/js/component/navbar.js, src/front/styles/home.css
src/front/js/component/contactForm.js: change name input.
src/front/js/component/navbar.js: change names of login and register.
src/front/styles/home.css: change width to join class.
=> Change names

src/front/js/component/OrganizacionesCards.js, src/front/js/pages/Organizaciones.js
src/front/js/component/OrganizacionesCards.js: Se creó este componente para poder trabajar llas cards en un componente diferente. src/front/js/pages/Organizaciones.js: Agregé el banner principal, los textos, el component de cards, componente auxiliar-banner-text, componente sponsor y su footer.
=> Se agregó la vista de Organizaciones

migrations/env.py, src/api/models.py, src/front/js/component/auxiliarGreenTwo.js, src/front/js/component/auxiliarWhiteFive.js, src/front/js/component/auxiliarWhiteFour.js, src/front/js/component/campaignBannerCopy.js, src/front/js/component/causasCards.js, src/front/js/component/historiaBanner.js, src/front/js/component/mainBanner.js, src/front/js/component/partnersBanner.js, src/front/js/component/volunteersBanner.js, src/front/js/component/volunteersBannerCopy.js, src/front/js/pages/Causas.js, src/front/js/pages/Organizaciones.js, src/front/js/pages/home.js, src/front/styles/home.css
=> [layout fix]

src/front/js/component/campaignBanner.js, src/front/js/component/fatFooter.js, src/front/js/component/mainBanner.js, src/front/js/component/partnersBanner.js, src/front/js/component/volunteersBanner.js, src/front/styles/home.css
=> [Button style fix]

package-lock.json, package.json, src/front/js/store/flux.js
[Started register login functionality]
=> [Started register login functionality]

src/front/js/store/flux.js
[register-login functionality working]
=> [register-login functionality tested]

src/front/js/store/flux.js
Started add-event functionality
=> Started add-event functionality

src/front/js/component/DataCampaign.js, src/front/js/component/cardsCampaigns.js, src/front/js/pages/Campaign.js
[Added campaign cards component]
=> [Added campaign cards component]

src/front/js/component/DataOrganizations.js, src/front/js/component/cardsOrgs.js, src/front/js/pages/Organizaciones.js
=> [Added organizations cards]

src/front/js/component/causasCards.js, src/front/js/component/infoAmbiente.js, src/front/js/component/infoSalud.js, src/front/js/component/infoSociedad.js, src/front/js/layout.js, src/front/styles/home.css
Se añadió los jumbotrones de causas.
=> Se añadió los jumbotrones de causas.

src/front/js/component/cardsOrgs.js, src/front/js/pages/Organizaciones.js
"updated organization layout and cards"
=> "updated organization layout and cards"

src/front/js/store/flux.js
[add event functionality done]
=> [add event functionality done]

src/front/js/store/flux.js
[Event attendance and list fetch done]
=> [Event attendance and list fetch done]

src/front/js/component/infoAmbiente.js, src/front/js/component/infoPartner.js, src/front/js/component/infoSalud.js, src/front/js/component/infoSociedad.js, src/front/js/component/partnersBanner.js, src/front/js/layout.js, src/front/styles/home.css
- A los componentes de infoAmbiente, infoSalud, infoSociedad se les agrego el Fatfooter.
- src/front/js/component/infoPartner.js: Jumbotron con información de el Partnership.
- src/front/js/component/partnersBanner.js: Se cambió la ruta de Link en el botón.
- src/front/js/layout.js: Se agregó ruta.
- src/front/styles/home.css: Se agregó el heigth a la clase container-jumbotron.
=> Se agrego el jumbotron en el boton de el partnersBanner.

src/front/js/store/flux.js
=> [Added delete functionality]

src/front/js/component/cardsCampaigns.js
=> campaign cards update

src/front/js/pages/UnirseOrganizacion.js, src/front/js/pages/UnirseVoluntario.js, src/front/styles/home.css
=> updated button

package-lock.json, package.json, src/front/js/component/formOrgAgregarEvento.js, src/front/js/component/modal/addEvent.js, src/front/js/component/perfilOrg.js, src/front/styles/home.css
"Added create-event modal to org profile"
=> "Added create-event modal to org profile"
